-- Seed appweb.dica_codes (genere depuis scripts/dica.xlsm)
CREATE TABLE IF NOT EXISTS appweb.dica_codes (code_dica TEXT PRIMARY KEY, description TEXT, traitement TEXT);
INSERT INTO appweb.dica_codes (code_dica, description, traitement) VALUES
('AMEND_CHAUX','Amendement par chaulage','NC'),
('AMEND_FER','Amendement par fertilisation','NC'),
('AMEND_ORG','Amendement organique','NC'),
('ANN','Annélation','NC'),
('BRU','Brûlage dirigé','NC'),
('CAS','Coupe d''assainissement','Coupe'),
('CJB','Coupe de jardinage par bandes','Coupe'),
('CJB-EMR','Coupe de jardinage par bandes avec éclaircie dans la matrice résiduelle','Coupe'),
('CJP','Coupe de jardinage par pied d''arbres','Coupe'),
('CJP-AM','Coupe de jardinage par pied d''arbres phase d''amélioration','Coupe'),
('CJPG','Coupe de jardinage par pied d''arbres et groupe d''arbres','Coupe'),
('CJPG-AM','Coupe de jardinage par pied d''arbres et groupe d''arbres phase d''amélioration','Coupe'),
('CJT','Coupe de jardinage par trouées','Coupe'),
('CJT-EMR','Coupe de jardinage par trouées avec éclaircie dans la matrice résiduelle','Coupe'),
('CPHRS-BOUQ','Coupe avec protection de la haute régénération et des sols avec legs biologiques par bouquets','Coupe'),
('CPHRS-ILOT','Coupe avec protection de la haute régénération avec legs biologiques par îlots','Coupe'),
('CPHRS-SLEG','Coupe avec protection de la haute régénération et des sols sans legs biologiques','Coupe'),
('CPHRS-TIGE','Coupe avec protection de la haute régénération et des sols avec legs biologiques par tiges individuelles','Coupe'),
('CPI_CP-ENS_B','Coupe progressive irrégulière (CPI), par bandes','Coupe'),
('CPI_CP-ENS_U','Coupe progressive irrégulière à couvert permanent phase d''ensemencement uniforme','Coupe'),
('CPI_CP-SEC_B','Coupe progressive irrégulière à couvert permanent phase secondaire ou d''abri par bandes','Coupe'),
('CPI_CP-SEC_U','Coupe progressive irrégulière à couvert permanent phase secondaire ou d''abri uniforme','Coupe'),
('CPI_RL-1INR_ENS','Coupe progressive irrégulière à régénération lente en 1 intervention et abandon du volume résiduel, phase d''ensemencement','Coupe'),
('CPI_RL-1INR_MUL','Coupe progressive irrégulière à régénération lente en 1 intervention et abandon du volume résiduel, Multiples phases','Coupe'),
('CPI_RL-1INR_SEC','Coupe progressive irrégulière à régénération lente en 1 intervention et abandon du volume résiduel, phase secondaire','Coupe'),
('CPI_RL-2I_ENS','Coupe progressive irrégulière à régénération lente en 2 interventions phase d''ensemencement','Coupe'),
('CPI_RL-2I_F','Coupe progressive irrégulière à régénération lente en 2 interventions phase finale','Coupe'),
('CPI_RL-2I_MUL','Coupe progressive irrégulière à régénération lente en 2 interventions et abandon du volume résiduel','Coupe'),
('CPI_RL-2I_SEC','Coupe progressive irrégulière à régénération lente en 2 interventions phase secondaire ou d''abri','Coupe'),
('CPI_RL-3I_ENS','Coupe progressive irrégulière à régénération lente en 3 interventions phase d''ensemencement','Coupe'),
('CPI_RL-3I_F','Coupe progressive irrégulière à régénération lente en 3 interventions phase finale','Coupe'),
('CPI_RL-3I_MUL','Coupe progressive irrégulière à régénération lente en 3 interventions et abandon du volume résiduel, Multiples phases','Coupe'),
('CPI_RL-3I_SEC','Coupe progressive irrégulière à régénération lente en 3 interventions phase secondaire ou d''abri','Coupe'),
('CPI_RL-MUL','Coupe progressive irrégulière à régénération lente par cas type phases multiples','Coupe'),
('CPI_RL-PR','Coupe progressive irrégulière à régénération lente phase préparatoire','Coupe'),
('CPI_TA','Coupe progressive irrégulière par trouées agrandies','Coupe'),
('CPPTM_DIS','Coupe avec protection des petites tiges marchandes discontinue sans ajout de legs biologiques additionnels','Coupe'),
('CPPTM_DIS-BOUQ','Coupe avec protection des petites tiges marchandes discontinue avec ajout de legs biologiques par bouquets','Coupe'),
('CPPTM_DIS-ILOT','Coupe avec protection des petites tiges marchandes discontinue avec ajout de legs biologiques par îlots','Coupe'),
('CPPTM_U','Coupe avec protection des petites tiges marchandes uniforme','Coupe'),
('CPR_BA','Coupe progressive régulière (CPR), par bandes','Coupe'),
('CPR_T','Coupe progressive régulière (CPR), par trouées','Coupe'),
('CPR_U-ENS','Coupe progressive régulière uniforme phase d''ensemencement','Coupe'),
('CPR_U-F_BOUQ','Coupe progressive régulière uniforme phase finale avec legs biologiques par bouquets','Coupe'),
('CPR_U-F_ILOT','Coupe progressive régulière uniforme phase finale avec legs biologiques par îlots','Coupe'),
('CPR_U-F_SLEG','Coupe progressive régulière uniforme phase finale sans legs biologiques','Coupe'),
('CPR_U-F_TIGE','Coupe progressive régulière uniforme phase finale avec legs biologiques par tiges individuelles','Coupe'),
('CPR_U-PR','Coupe progressive régulière uniforme phase préparatoire','Coupe'),
('CPR_U-SEC','Coupe progressive régulière uniforme phase secondaire','Coupe'),
('CPRS_BA','Coupe avec protection de la régénération et des sols (CPRS), Bandes (1H > Largeur < distance ensemencement)','Coupe'),
('CPRS_DA','Coupe avec protection de la régénération et des sols (CPRS), Damiers','Coupe'),
('CPRS_PA','Coupe avec protection de la régénération et des sols (CPRS), Parquets (Largeur < distance ensemencement généralement de 0,5 ha à 2 ha)','Coupe'),
('CPRS_T','Coupe avec protection de la régénération et des sols (CPRS), Trouées (1H à 2H)','Coupe'),
('CPRS_U-BOUQ','Coupe avec protection de la régénération et des sols uniforme avec legs biologiques par bouquets','Coupe'),
('CPRS_U-ILOT','Coupe avec protection de la régénération et des sols uniforme avec legs biologiques par îlots','Coupe'),
('CPRS_U-SLEG','Coupe avec protection de la régénération et des sols uniforme sans legs biologiques','Coupe'),
('CPRS_U-TIGE','Coupe avec protection de la régénération et des sols uniforme avec legs biologiques par tiges individuelles','Coupe'),
('CRS-BOUQ','Coupe avec réserve de semenciers avec legs biologiques par bouquets','Coupe'),
('CRS-ILOT','Coupe avec réserve de semenciers avec legs biologiques par îlots','Coupe'),
('CRS-SLEG','Coupe avec réserve de semenciers sans legs biologiques','Coupe'),
('CRS-TIGE','Coupe avec réserve de semenciers avec legs biologiques par tiges individuelles','Coupe'),
('CS-BOUQ','Coupe de succession avec ajout de legs biologiques par bouquets','Coupe'),
('CS-ILOT','Coupe de succession avec ajout de legs biologiques par îlots','Coupe'),
('CS-SLEG','Coupe de succession sans ajout de legs biologiques additionnels','Coupe'),
('CS-TIGE','Coupe de succession avec ajout de legs biologiques par tiges individuelles','Coupe'),
('CTSP_BA','Coupe totale sans protection par bandes','Coupe'),
('CTSP_DA','Coupe totale sans protection en damier','Coupe'),
('CTSP_PA','Coupe totale sans protection en parquets','Coupe'),
('CTSP_T','Coupe totale sans protection par trouées','Coupe'),
('CTSP_U-BOUQ','Coupe totale sans protection uniforme avec legs biologiques par bouquets','Coupe'),
('CTSP_U-ILOT','Coupe totale sans protection uniforme avec legs biologiques par îlots','Coupe'),
('CTSP_U-SLEG','Coupe totale sans protection uniforme sans legs biologiques','Coupe'),
('CTSP_U-TIGE','Coupe totale sans protection uniforme avec legs biologiques par tiges individuelles','Coupe'),
('DEBL-PART','Déblaiement sur une portion de la superficie','DEBL'),
('DEBL-PLEIN','Déblaiement sur l''ensemble de la superficie','DEBL'),
('DEBR','Débroussaillement',NULL),
('DEG_ANN','Dégagement par annellation de la végétation concurrente','DEG'),
('DEG_MEC','Dégagement par coupe mécanique de la végétation concurrente','DEG'),
('DEG_PHYB','Dégagement avec des phytocides biologiques','DEG'),
('DEG_PHYC','Dégagement avec des phytocides chimiques','DEG'),
('DEP','Dépressage','EP'),
('DR_APP','Drainage d''appoint sur une portion de la superficie',NULL),
('DR_SYS','Drainage systématique sur l''ensemble de la superficie',NULL),
('EC_MIXTE-BAS','Éclaircie commerciale mixte par le bas','Coupe'),
('EC_MIXTE-HAUT','Éclaircie commerciale mixte par le haut','Coupe'),
('EC_MIXTE-NEUTRE','Éclaircie commerciale mixte par le haut et par le bas','Coupe'),
('EC_SEL-BAS','Éclaircie commerciale sélective par le bas','Coupe'),
('EC_SEL-HAUT','Éclaircie commerciale sélective par le haut','Coupe'),
('EC_SEL-NEUTRE','Éclaircie commerciale sélective par le haut et par le bas','Coupe'),
('EC_SYS','Éclaircie commerciale systématique','Coupe'),
('EJ_P-CLAS','Éclaircie jardinatoire par pieds d''arbre phase finale ou classique','Coupe'),
('EJ_PG-CLAS','Éclaircie jardinatoire par pieds d''arbre et groupes d''arbre phase finale ou classique','Coupe'),
('EJ_PG-INI','Éclaircie jardinatoire par pieds d''arbre et groupes d''abre phase initiale','Coupe'),
('EJ_P-INI','Éclaircie jardinatoire par pieds d''arbre phase initiale','Coupe'),
('ELAG','Élagage','NC'),
('ENS_AE','Ensemencement aérien','NC'),
('ENS_TER-MANU','Ensemencement terrestre manuel','NC'),
('ENS_TER-MEC','Ensemencement terrestre mécanisé','NC'),
('EPC_PUITS','Éclaircie précommerciale par puits de lumière','EPC'),
('EPC_SYS','Éclaircie précommerciale systématique','EPC'),
('ETR','Élimination des tiges résiduelles','NC'),
('NET_ANN','Nettoiement par annellation de la végétation concurrente','NET'),
('NET_MEC','Nettoiement par coupe mécanique de la végétation concurrente','NET'),
('NET_PHYB','Nettoiement avec des phytocides biologiques','NET'),
('NET_PHYC','Nettoiement avec des phytocides chimiques','NET'),
('PATS_COMM','Traitement en expérimentation dans le processus d''analyse lié aux traitements sylvicoles commerciaux','NC'),
('PATS_NCOEP','Traitement d''éducation de peuplement en expérimentation dans le processus d''analyse lié aux traitements sylvicoles NON commerciaux','EP'),
('PATS_NCORA','Traitement de régénération artificielle en expérimentation dans le processus d''analyse lié aux traitements sylvicoles NON commerciaux','REB'),
('PATS_NCOTS','Traitement du site en expérimentation dans le processus d''analyse lié aux traitements sylvicoles NON commerciaux',NULL),
('PL_AGRO-MEL','Plantation par systèmes agroforestiers avec mélange d''essences','REB'),
('PL_AGRO-MONO','Plantation par systèmes agroforestiers monospécifique','REB'),
('PL_ENR-MEL','Enrichissement par plantation d''un mélange d''essences','REB'),
('PL_ENR-MONO','Enrichissement par plantation d''une seule essence','REB'),
('PL_REG-MEL','Plantation par regarni avec mélange d''essences','REG'),
('PL_REG-MONO','Plantation par regarni monospécifique','REG'),
('PL_U-MEL','Plantation uniforme avec mélange d''essences','REB'),
('PL_U-MONO','Plantation uniforme monospécifique','REB'),
('RECUP_CHABLIS-PART','Coupe partielle de récupération ( < 75 % ST) après chablis','Coupe'),
('RECUP_CHABLIS-TOT','Coupe totale de récupération ( > 75 % ST) après chablis','Coupe'),
('RECUP_FEU-PART','Coupe partielle de récupération ( < 75 % ST) après feu','Coupe'),
('RECUP_FEU-TOT','Coupe totale de récupération ( > 75 % ST) après feu','Coupe'),
('RECUP_INSECT-PART','Coupe partielle de récupération ( < 75 % ST) après épidémie d''insectes','Coupe'),
('RECUP_INSECT-TOT','Coupe totale de récupération ( > 75 % ST) après épidémie d''insectes','Coupe'),
('RECUP_MALADIE-PART','Coupe partielle de récupération ( < 75 % ST) après maladie','Coupe'),
('RECUP_MALADIE-TOT','Coupe totale de récupération ( > 75 % ST) après maladie','Coupe'),
('RML','Récupération de la matière ligneuse','Coupe'),
('RPLB_1500','Récolte patrtielle dans une lisière boisée (1500 tiges de 2 cm et +)','Coupe'),
('RPLB_500','Récolte patrtielle dans une lisière boisée (500 tiges de 10 cm et +)','Coupe'),
('RPLB_700','Récolte patrtielle dans une lisière boisée (700 tiges de 10 cm et +)','Coupe'),
('SCA_DEBL_MONT-PLEIN','Déblaiement des résidus de coupe combiné à un scarifiage en monticule avec excavatrice','DEBL'),
('SCA_DECAP-PART','Scarifiage par décapage par placeau sur une portion de la superficie','SCA'),
('SCA_DECAP-PLEIN','Scarifiage par décapage par placeau sur l''ensemble de la superficie','SCA'),
('SCA_HERS-PART','Scarifiage par hersage/Labour sur une portion de la superficie','SCA'),
('SCA_HERS-PLEIN','Scarifiage par hersage/Labour sur l''ensemble de la superficie','SCA'),
('SCA_INV-PART','Scarifiage par inversion par placeau sur une portion de la superficie','SCA'),
('SCA_INV-PLEIN','Scarifiage par inversion par placeau sur l''ensemble de la superficie','SCA'),
('SCA_MIX-PART','Scarifiage par mixage par placeau sur une portion de la superficie','SCA'),
('SCA_MIX-PLEIN','Scarifiage par mixage par placeau sur l''ensemble de la superficie','SCA'),
('SCA_MONT-PART','Scarifiage en monticules sur une portion de la superficie','SCA'),
('SCA_MONT-PLEIN','Scarifiage en monticules sur l''ensemble de la superficie','SCA'),
('SCA_SILL-PART','Scarifiage en sillons sur une portion de la superficie','SCA'),
('SCA_SILL-PLEIN','Scarifiage en sillons sur l''ensemble de la superficie','SCA'),
('TAILFOR_CLASS','Taille de formation classique','NC'),
('TAILFOR_SYST','Taille de formation systématique','NC'),
('TAILPHY','Taille phytosanitaire','NC'),
('DEG_AVT','DEG avant traitement','DEG_AVT'),
('NET_AVT','NET avant traitement','NET_AVT'),
('REB_AVT','REB avant traitement','REB_AVT'),
('EPC_AVT','EPC avant traitement','EPC_AVT')
ON CONFLICT (code_dica) DO UPDATE SET description=EXCLUDED.description, traitement=EXCLUDED.traitement;
