-- Seed appweb.field_definitions (catalogue, 1 jeu complet par year_suffix)
INSERT INTO appweb.field_definitions(entity,year_suffix,field_name,label,data_type,source,requirement,list_name,validation_rule,min_value,max_value,is_editable,display_order) VALUES
('ue','2026-2027','unite_d_echantillonnage_ue','UE','texte','auto','R',NULL,NULL,NULL,NULL,FALSE,1),
('ue','2026-2027','region','Région','liste','manuel','R','region',NULL,NULL,NULL,TRUE,2),
('ue','2026-2027','rayon','Rayon','decimal','manuel','R',NULL,NULL,'0','12',TRUE,3),
('ue','2026-2027','gradient_intensite','Gradient d intensité','liste','manuel','R','gradient_intensite',NULL,NULL,NULL,TRUE,4),
('ue','2026-2027','code_dica','Code DICA','liste','manuel','R','dica_codes',NULL,NULL,NULL,TRUE,5),
('ue','2026-2027','traitement','Traitement','texte','derive','O',NULL,NULL,NULL,NULL,FALSE,6),
('ue','2026-2027','plant_ha','Plant/ha','entier','manuel','C',NULL,'plant_ha_plantation','600','2000',TRUE,7),
('ue','2026-2027','traitement_ps','Préparation de terrain','liste','manuel','C','traitement_ps','traitement_ps_prep',NULL,NULL,TRUE,8),
('ue','2026-2027','denombrement_cn','Dénombrement CN','entier','manuel','C',NULL,'denombrement_cn_avt','0','1000',TRUE,9),
('ue','2026-2027','taux_occ_andain','Taux occ. andain','entier','manuel','C',NULL,'taux_occ_andain_abit','0','100',TRUE,10),
('ue','2026-2027','no_prescription','N° prescription','texte','auto','O',NULL,NULL,NULL,NULL,TRUE,11),
('ue','2026-2027','secteur_intervention','Secteur d intervention','texte','auto','O',NULL,NULL,NULL,NULL,TRUE,12),
('ue','2026-2027','chantier','Chantier','texte','auto','O',NULL,NULL,NULL,NULL,TRUE,13),
('ue','2026-2027','uaf','UAF','texte','auto','O',NULL,NULL,NULL,NULL,TRUE,14),
('ue','2026-2027','code_ratf','Code RATF','liste','auto','O','code_ratf',NULL,NULL,NULL,TRUE,15),
('ue','2026-2027','contrat','Contrat','texte','auto','O',NULL,NULL,NULL,NULL,TRUE,16),
('ue','2026-2027','projet','Projet','texte','auto','O',NULL,NULL,NULL,NULL,TRUE,17),
('ue','2026-2027','ha_prescription','Superficie (ha)','decimal','auto','O',NULL,NULL,NULL,NULL,TRUE,18),
('ue','2026-2027','entrepreneur_travaux','Entrepreneur','texte','auto','O',NULL,NULL,NULL,NULL,TRUE,19),
('ue','2026-2027','debut','Date début','date','auto','O',NULL,NULL,NULL,NULL,TRUE,20),
('ue','2026-2027','fin','Date fin','date','auto','O',NULL,NULL,NULL,NULL,TRUE,21),
('ue','2026-2027','nb_parcelle_ue','Nb parcelles UE','entier','manuel','O',NULL,NULL,NULL,NULL,TRUE,22),
('ue','2026-2027','parcelle_faite','Parcelle faite','liste','manuel','O','parcelle_faite',NULL,NULL,NULL,TRUE,23),
('ue','2026-2027','directive_op','Directive OP','texte','manuel','O',NULL,NULL,NULL,NULL,TRUE,24),
('ue','2026-2027','ha_net','Superficie nette (ha)','decimal','manuel','O',NULL,NULL,NULL,NULL,TRUE,25),
('ue','2026-2027','origine','Origine','texte','manuel','O',NULL,NULL,NULL,NULL,TRUE,26),
('ue','2026-2027','preparation_de_terrain','Préparation terrain (txt)','texte','manuel','O',NULL,NULL,NULL,NULL,TRUE,27),
('ue','2026-2027','type_de_degagement','Type de dégagement','texte','manuel','O',NULL,NULL,NULL,NULL,TRUE,28),
('ue','2026-2027','equip_utilise','Équipement utilisé','liste','manuel','O','equip_utilise',NULL,NULL,NULL,TRUE,29),
('ue','2026-2027','methode_andains','Méthode andains','liste','manuel','O','methode_andains',NULL,NULL,NULL,TRUE,30),
('ue','2026-2027','nb_si_reboisement','Nb SI reboisement','entier','manuel','O',NULL,NULL,'0','10',TRUE,31),
('ue','2026-2027','plant_max','Plant max','decimal','manuel','O',NULL,NULL,NULL,NULL,TRUE,32),
('ue','2026-2027','plant_reboise','Plant reboisé','decimal','manuel','O',NULL,NULL,NULL,NULL,TRUE,33),
('ue','2026-2027','ms_propice','MS propice','decimal','manuel','O',NULL,NULL,NULL,NULL,TRUE,34),
('ue','2026-2027','note_1','Note','texte','manuel','O',NULL,NULL,NULL,NULL,TRUE,35),
('ue','2026-2027','andain','Andain','decimal','manuel','O',NULL,NULL,NULL,NULL,TRUE,36),
('ue','2026-2027','entre_andain','Entre-andain','decimal','manuel','O',NULL,NULL,NULL,NULL,TRUE,37),
('ue','2026-2027','stocking_av_tr','Stocking avant traitement','decimal','manuel','O',NULL,NULL,NULL,NULL,TRUE,38)
ON CONFLICT(entity,year_suffix,field_name) DO NOTHING;
